apiVersion: v1
kind: Pod
metadata:
  name: pgadmin-full
  labels:
    app: pgadmin-full
spec:
  volumes:
  - name: postgredb
      persistentVolumeClaim:
        claimName: postgres-pv-claim

  containers :
  - name: postgres
          image: postgres:11
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres_password
                  name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
  
  - name: pgadmin
    - env:
          - name: PGADMIN_DEFAULT_EMAIL
            value: user@e-mail.com
          - name: PGADMIN_DEFAULT_PASSWORD
            value: password
          - name: PGADMIN_PORT
            value: "80"
          image: dpage/pgadmin4
          imagePullPolicy: IfNotPresent
          name: pgadmin
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          resources:
            limits:
              memory: 1024Mi
